config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :projects do 
     resources :funds
   end
   resources :funds
   resources :categories
  get 'projects/:id/delete' => 'projects#destroy', as: :destroy_project
  get 'users/:id' => 'users/profiles#show', as: :profile
  get '/auth/facebook/callback' => 'sessions#create'
  root 'projects#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :project_categories
  has_many :projects, through: :project_categories

  def ending_projects
    self.projects.where("end_date >= ?", Date.today).order("end_date asc")
  end
end

app/models/fund.rb
class Fund < ActiveRecord::Base
  validates :amount, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :enough_in_balance
  belongs_to :project
  belongs_to :backer, class_name: "User"

  def submit
    self.backer.balance -= self.amount
    self.project.user.balance += self.amount
    self.project.user.save
    self.backer.save
  end

  def enough_in_balance
    if self.amount > self.backer.balance
      errors.add(:amount)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :end_date, presence: true
  validates :fund_goal, presence: true
  belongs_to :user
  has_many :funds
  has_many :backers, -> { distinct }, through: :funds
  validate :end_date_cannot_be_in_the_past
  has_many :project_categories
  has_many :categories, through: :project_categories

  def end_date_cannot_be_in_the_past
    if end_date.present? && end_date < Date.today
      errors.add(:end_date)
    end
  end 

   def category_ids=(ids)
     ids.each do |id|
       if (id != "")
         category = Category.find(id)
         if !self.categories.include?(category)
           self.categories << category
         end
       end
     end
   end


   def new_category=(title)
      category = Category.find_or_create_by(title: title)
      if !self.categories.include?(category)
       self.categories << category
      end
    end

  def self.ending_projects
    @ending_projects = Project.where("end_date >= ?", Date.today).order("end_date asc")
  end


  def funded
    sum = 0
    self.funds.each do |f|
      if f.amount
        sum += f.amount
      end
    end
    sum
  end

  def funded_percent
    (self.funded.to_f / self.fund_goal.to_f * 100).round
  end

  def user_email
    User.find(self.user_id).email
  end


end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  belongs_to :project
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :funds, foreign_key: "backer_id"
  has_many :projects

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def backed_projects
    backed_projects = []
    self.funds.each do |p|
      backed_projects << Project.find(p.project_id)
    end
    backed_projects.uniq
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @categories}
    end
  end

  def show
    @category = Category.find(params[:id])
  end


  private
  def fund_params
   params.require(:fund).permit(:backer_id, :project_id, :amount)
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  def index
    if params[:project_id]
      @project = Project.find(params[:project_id])
      @funds = @project.funds
    else
      @funds = Fund.all
    end
  end

  def create
    @fund = Fund.new(fund_params)
    if @fund.save
      @fund.submit
      redirect_to project_path(@fund.project_id), notice: "Successfully funded to this project!"
    else
      @project = Project.find(@fund.project_id)
      render "/projects/show"
    end
  end

  private
  def fund_params
   params.require(:fund).permit(:backer_id, :project_id, :amount)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @ending_projects = Project.ending_projects
  end

  def show
    if user_signed_in?
      @fund = Fund.new(backer_id: current_user.id, project_id: @project.id)
    else

    end
  end

  def new
    if user_signed_in?
      @project = Project.new(user_id: current_user.id)
    else
      redirect_to home_path, alert: "You must be signed in to do that"
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project), notice: "Project successfully created!"
    else
      render :new
    end
  end
 
  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project successfully destroyed"
  end


  private
  def set_project
    @project = Project.find(params[:id])
    redirect_to projects_path, alert: "Project with that id not found" if @project.nil?
  end

  def project_params
    params.require(:project).permit(:user_id, :title, :description, :fund_goal, :end_date, :new_category, category_ids:[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
    user = User.find_or_create_by(:uid => auth['uid']) do |u|
      u.email = auth['info']['email']
    end
    sign_in(:user, user)
    session[:user_id] = user.id
    redirect_to root_path
  end
 
  def auth
    request.env['omniauth.auth']
  end
 
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def show
    if @user.id == current_user.id
      render :show_self
    end
  end

  private
  def set_user
    if user_signed_in?
      @user = User.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def show_edit
    if current_user
      if (@project.user_id == current_user.id) or (current_user.admin?)
        link_to "(edit)", edit_project_path(@project)
      end
    end
  end

  def show_delete
    if current_user
      if (@project.user_id == current_user.id) or (current_user.admin?)
        link_to "(delete)", destroy_project_path(@project)
      end
    end
  end

end

app/views/categories/index.html.erb
<h1>All Categories:</h1>
<% @categories.each do |c| %>
  <h4><%= link_to c.title, category_path(c) %></h4>
<% end %>

app/views/categories/show.html.erb
<h1>Projects related to <%= @category.title %></h1>
<table class="table table-hover">
  <th>Project Name</th>
  <th>Amount Funded</th>
  <th>End Date</th>
  <% @category.ending_projects.each do |p| %>
    <tr>
      <td><h2><%= link_to p.title, project_path(p)%></h2></td>
      <td><p><%= p.funded %> / <%= p.fund_goal%> ( <%= p.funded_percent %>%)</p></td>
      <td><p><%= p.end_date %></p>
    </tr>
  <% end %>
</table>

app/views/funds/index.html.erb
<h1>All Funds for <%= @project.title%></h1>
<% @project.funds.each do |f| %>
  <p>Email: <%= User.find(f.backer_id).email%></p>
  <p>Amount: <%= f.amount %></p>
  <br>
<% end %>

app/views/layouts/_header.html.erb
<ul class="nav navbar-nav">  
<% if user_signed_in? %>
     <li class="navbar-text">Signed in as <%= current_user.email %></li>
     <li><%= link_to "Sign out", destroy_user_session_url, method: :delete %></li>
     <li><%= link_to "Profile", profile_path(current_user) %></li>
     <li><%= link_to "Home", root_path %></li>
     <li><%= link_to "Categories", categories_path %></li>
     <li><%= link_to "Start a new project", new_project_path %></li>
   <% else %>
     <li><%= link_to "Sign up", new_user_registration_path %></li>
     <li><%= link_to "Sign in", new_user_session_path %></li>
     <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
     <li><%= link_to "Home", root_path %></li>
   <% end %>
</ul><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @project do |f| %>
  <%= f.hidden_field :user_id %><br>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br><br>
  <%= f.label :fund_goal %><br>
  <%= f.number_field :fund_goal %><br><br>
  <label for"project_end_date">End Date (yyyy/mm/dd)</label><br>
  <%= f.text_field :end_date %><br><br>
  <label>Select Relevant Categories:</label><br>
  <%= collection_check_boxes(:project, :category_ids, Category.all, :id, :title) %><br>
  <label>And/Or Create a New Category:</label><br>
  <input type="text" name="project[new_category]" id="new_project_category"><br><br>
  <%= f.submit %><br>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project: </h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Welcome to FundMyProject</h1>
<table class="table table-hover">
  <th>Project Name</th>
  <th>Amount Funded</th>
  <th>End Date</th>
  <% @ending_projects.each do |p| %>
    <tr>
      <td><h2><%= link_to p.title, project_path(p)%></h2></td>
      <td><p><%= p.funded %> / <%= p.fund_goal%> ( <%= p.funded_percent %>%)</p></td>
      <td><p><%= p.end_date %></p>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>Create new project: </h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1 id="<%= @project.id %>"><%= @project.title%> <%= show_edit %> <%= show_delete %></h1>
<p><%= @project.description %></p>
<p>Owned by: <%= link_to @project.user_email, profile_path(@project.user)%></p>
<p id="funded">Amount Funded: <%= @project.funded %> / <%= @project.fund_goal%> ( <%= @project.funded_percent %>% )</p>
<p>End Date: <%= @project.end_date %></p>
<br>
<h4>Associated Categories: </h4>
<% @project.categories.each do |c| %>
  <p><%= link_to c.title, category_path(c)%></p>
<% end %>
<h4>Current Backers:</h4>
<div id="current_backers">
<% @project.backers.each do |b| %>
  <p><%= link_to b.email, profile_path(b) %></p>
<% end %>
</div>
<br>
<% if user_signed_in? %>
  <p>Interested? Fund an amount below:</p>
  <%= form_for @fund do |f| %>
    <%= f.hidden_field :backer_id %>
    <%= f.hidden_field :project_id %>
    <%= f.number_field :amount %>
    <%= button_to 'Fund', funds_path %>
    <% end %>
<% else %>
  <p>Want to help fund this project? <%= link_to "Sign In", new_user_session_path %></p>
<% end %>
<br>
<div id="project_funds">
<button type="button" class="btn btn-default navbar-btn">Check Out All the Funds for this Project</button>
</div>

app/views/users/profiles/show.html.erb
<h1><%= @user.email%>'s profile</h1>
<br>
<h2>Owned projects:</h2>
<% @user.projects.each do |p| %>
  <p><%= link_to p.title, project_path(p) %></p>
<% end %>

app/views/users/profiles/show_self.html.erb
<h1>Your profile</h1>
<br>
<h2>Available Balance ($): <%= @user.balance %></h2>
<h2>Your owned projects:</h2>
<% @user.projects.each do |p| %>
  <p><%= link_to p.title, project_path(p) %></p>
<% end %>
<h2>Your backed projects:</h2>
<% @user.backed_projects.each do |p| %>
  <p><%= link_to p.title, project_path(p) %></p>
<% end %>